version: '3.3'
services:
  web:
    build: ./
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 # python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/project/
      - static_volume:/home/web/staticfiles
    expose:
      - 8000
    env_file:
      - .docker.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .docker.env
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
    - static_volume:/home/web/staticfiles
volumes:
  postgres_data:
  static_volume: